//! # maestro-algorithm
//!
//! The 7-Phase Algorithm Pipeline ported from Maestro's PAI framework,
//! redesigned to integrate with OpenFang's workflow engine and Rig.rs
//! model abstraction layer.
//!
//! ## Phases
//!
//! 1. **OBSERVE** — Gather context, read environment, assess current state
//! 2. **ORIENT** — Analyze the task, decompose complexity, identify constraints
//! 3. **PLAN** — Generate execution plan with Ideal State Criteria (ISC)
//! 4. **EXECUTE** — Run the plan steps (delegates to OpenFang agents)
//! 5. **VERIFY** — Mechanically verify ISC satisfaction against output
//! 6. **LEARN** — Capture learnings, patterns, and failure modes
//! 7. **ADAPT** — Update algorithm parameters based on accumulated learnings
//!
//! ## Integration with OpenFang
//!
//! This crate does NOT replace OpenFang's `openfang-kernel::workflow`.
//! Instead, it provides a higher-level orchestration pattern that can be
//! registered as a workflow template. OpenFang's supervisor dispatches
//! agents; this crate defines WHAT those agents should do at each phase.
//!
//! ## HONEST GAPS (things that need work)
//!
//! - The ADAPT phase is conceptual only — no real parameter mutation yet
//! - ISC generation is LLM-dependent and can produce vague criteria
//! - No integration with OpenFang's task board for multi-agent EXECUTE
//! - Learning storage is local; needs OpenFang's memory system integration
//! - Retry logic is simplistic (fixed count, no exponential backoff)

pub mod error;
pub mod executor;
pub mod isc;
pub mod phases;
pub mod prompts;
pub mod types;

pub use executor::AlgorithmExecutor;
#[allow(unused_imports)]
pub use types::*;

// ── Core Types ──────────────────────────────────────────────────────────────

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// A unique identifier for an algorithm execution run.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct RunId(pub Uuid);

impl RunId {
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }
}

impl Default for RunId {
    fn default() -> Self {
        Self::new()
    }
}

/// The 7 phases of the Maestro Algorithm.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "UPPERCASE")]
pub enum Phase {
    Observe,
    Orient,
    Plan,
    Execute,
    Verify,
    Learn,
    Adapt,
}

impl std::fmt::Display for Phase {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Phase::Observe => write!(f, "OBSERVE"),
            Phase::Orient => write!(f, "ORIENT"),
            Phase::Plan => write!(f, "PLAN"),
            Phase::Execute => write!(f, "EXECUTE"),
            Phase::Verify => write!(f, "VERIFY"),
            Phase::Learn => write!(f, "LEARN"),
            Phase::Adapt => write!(f, "ADAPT"),
        }
    }
}

/// Ideal State Criterion — a measurable success condition.
///
/// HONEST NOTE: In Maestro's original implementation, ISC criteria were
/// generated by the LLM and often vague ("ensure quality"). A proper
/// implementation needs structured templates and human-reviewable criteria.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdealStateCriterion {
    /// Unique criterion ID (e.g., "C1", "C2").
    pub id: String,
    /// Human-readable description of what must be true.
    pub description: String,
    /// Category: FUNCTIONAL, QUALITY, COMPLETENESS, CONSTRAINT.
    pub category: CriterionCategory,
    /// Weight for scoring (0.0 - 1.0). Defaults to equal weight.
    pub weight: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "UPPERCASE")]
pub enum CriterionCategory {
    Functional,
    Quality,
    Completeness,
    Constraint,
}

/// Result of verifying a single ISC criterion.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CriterionVerification {
    pub criterion_id: String,
    pub status: VerificationStatus,
    pub evidence: String,
    pub confidence: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum VerificationStatus {
    Satisfied,
    Partial,
    Failed,
}

/// A single learning captured during the LEARN phase.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Learning {
    pub category: LearningCategory,
    pub insight: String,
    pub context: String,
    pub actionable: bool,
    pub timestamp: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "UPPERCASE")]
pub enum LearningCategory {
    System,
    Algorithm,
    Failure,
    Synthesis,
    Reflection,
}

/// Complete result of an algorithm execution run.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AlgorithmResult {
    pub run_id: RunId,
    pub task_description: String,
    pub phase_outputs: Vec<PhaseOutput>,
    pub overall_satisfaction: f64,
    pub learnings: Vec<Learning>,
    pub started_at: DateTime<Utc>,
    pub completed_at: DateTime<Utc>,
    pub total_tokens_used: u64,
    pub total_cost_usd: f64,
}

/// Output from a single phase execution.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PhaseOutput {
    pub phase: Phase,
    pub output: serde_json::Value,
    pub tokens_used: u64,
    pub duration_ms: u64,
    pub model_used: String,
}
