//! # openfang-mcp-bridge
//!
//! MCP (Model Context Protocol) bridge for OpenFang Agent OS.
//!
//! ## What this crate is
//!
//! A protocol adapter that exposes OpenFang's tool surface to Claude Code
//! subprocesses (and other MCP clients) over stdio. One MCP server instance
//! per parent agent, scoped to that agent's identity and the capabilities
//! declared in its `agent.toml`.
//!
//! ## What this crate is NOT
//!
//! - It does NOT depend on `openfang-runtime`, `openfang-kernel`, or
//!   `openfang-memory` directly. The bridge consumes a narrow
//!   [`ToolDispatcher`] trait that the runtime exposes; the runtime owns
//!   identity, the kernel owns dispatch, the memory subsystem stays untouched.
//! - It does NOT define OpenFang's tool surface. Tools are declared by their
//!   owning crates and registered through the dispatcher.
//!
//! ## Project status
//!
//! Spike scaffold (ANAI-29). At this stage the bridge:
//! - Compiles as a standalone crate in the workspace.
//! - Ships a stdio binary (`openfang-mcp-bridge`) that responds to MCP
//!   `initialize` and `tools/list` with a single stub `ping` tool.
//! - Defines the [`ToolDispatcher`] seam trait (unused by the stub).
//!
//! Real tool surface mapping lands in ANAI-30. Identity threading lands in
//! ANAI-31. See ANAI-22 for the umbrella tracker.

pub mod protocol;

use std::sync::Arc;

use rmcp::{
    ErrorData as McpError, ServerHandler,
    handler::server::router::tool::ToolRouter,
    model::*,
    tool, tool_handler, tool_router,
};

/// Narrow seam between the bridge and the OpenFang runtime.
///
/// The runtime implements this trait and hands an `Arc<dyn ToolDispatcher>` to
/// the bridge at startup, scoped to a specific agent identity. The bridge
/// translates incoming MCP `tools/call` requests into [`ToolDispatcher::call`]
/// invocations.
///
/// **Identity is bound at construction time, not per-call.** A bridge instance
/// only ever speaks for one agent. This is the security invariant tracked by
/// ANAI-31.
#[async_trait::async_trait]
pub trait ToolDispatcher: Send + Sync {
    /// Identity of the agent this dispatcher is bound to. Used for audit
    /// logging and for cross-checking against `agent.toml` capabilities.
    fn agent_id(&self) -> &str;

    /// List of tool names this dispatcher will accept, derived from
    /// `agent.toml` capabilities. The bridge filters its advertised tool list
    /// against this set.
    fn allowed_tools(&self) -> Vec<String>;

    /// Invoke a tool by name with a JSON argument blob. The dispatcher is
    /// responsible for capability enforcement; the bridge MUST NOT assume the
    /// caller is trusted.
    async fn call(
        &self,
        tool_name: &str,
        args: serde_json::Value,
    ) -> Result<serde_json::Value, ToolDispatchError>;
}

/// Errors a [`ToolDispatcher`] can return. Bridge maps these to MCP errors.
#[derive(Debug, thiserror::Error)]
pub enum ToolDispatchError {
    #[error("unknown tool: {0}")]
    UnknownTool(String),
    #[error("tool '{0}' not permitted for this agent")]
    NotPermitted(String),
    #[error("invalid arguments for tool '{tool}': {reason}")]
    InvalidArgs { tool: String, reason: String },
    #[error("tool execution failed: {0}")]
    Execution(#[from] anyhow::Error),
}

/// The MCP server handler — wraps a [`ToolDispatcher`] and serves it over MCP.
///
/// In the spike scaffold the dispatcher is optional and unused; only the stub
/// `ping` tool is wired. ANAI-30 will replace `ping` with dispatcher-backed
/// tools.
#[derive(Clone)]
pub struct Bridge {
    #[allow(dead_code)] // wired in ANAI-30
    dispatcher: Option<Arc<dyn ToolDispatcher>>,
    // Read by code generated by `#[tool_router]` / `#[tool_handler]`; the
    // dead-code analyzer doesn't see those reads.
    #[allow(dead_code)]
    tool_router: ToolRouter<Bridge>,
}

#[tool_router]
impl Bridge {
    pub fn new(dispatcher: Option<Arc<dyn ToolDispatcher>>) -> Self {
        Self {
            dispatcher,
            tool_router: Self::tool_router(),
        }
    }

    #[tool(description = "Stub liveness check. Returns 'pong'. Replaced in ANAI-30 by dispatcher-backed tools.")]
    async fn ping(&self) -> Result<CallToolResult, McpError> {
        Ok(CallToolResult::success(vec![Content::text("pong")]))
    }
}

#[tool_handler]
impl ServerHandler for Bridge {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(
            ServerCapabilities::builder().enable_tools().build(),
        )
        .with_server_info(Implementation::from_build_env())
        .with_protocol_version(ProtocolVersion::V_2024_11_05)
        .with_instructions(
            "OpenFang MCP bridge (spike). Exposes OpenFang's tool surface to MCP clients. \
             Currently stubbed with a single `ping` tool; full tool surface lands in ANAI-30."
                .to_string(),
        )
    }
}
